name: Try to update clangd-for-modules

on:
  schedule:
    - cron: 0 1 * * *

jobs:
  try-to-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@4
      - run: |
          set curr_commit=$(git submodule status clangd-for-modules | awk '{print $1}')
          git submodule update --init --remote
          set new_commit=$(git submodule status clangd-for-modules | awk '{print $1}')
          if [ "$curr_commit" != "$new_commit" ]; then
            git add .
            git commit -m "update clangd-for-modules to $new_commit"
            git push
          fi
