name: Try to update clangd-for-modules

on:
  schedule:
    - cron: 0 1 * * *

  workflow_dispatch:

permissions:
  contents: write

jobs:
  try-to-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: update clangd-for-modules
        run: |
          git submodule update --init --remote --depth=1 clangd-for-modules
          commit=$(git submodule status clangd-for-modules | awk '{print $1}')
          echo "updated=$commit" >> "$GITHUB_OUTPUT"
          sed -i "N; N; s/#REPLACE.*/#REPLACE\ngit checkout $commit\n/" Dockerfile   

      - name: Commit updated submodule if changed
        uses: EndBug/add-and-commit@v9
        with:
          tag: commit-${{ steps.get-data.outputs.updated }}
