name: Try to update clangd-for-modules

on:
  schedule:
    - cron: 0 1 * * *

  workflow_dispatch:

jobs:
  try-to-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@4
      
      - id: get-data
        run: |
          git submodule status clangd-for-modules | awk '{print "original="$1}' >> "$GITHUB_OUTPUT"
          git submodule update --init --remote
          git submodule status clangd-for-modules | awk '{print "updated="$1}' >> "$GITHUB_OUTPUT" 

      - name: Commit updated submodule
        if: ${{ steps.get-data.outputs.original != steps.get-data.outputs.updated }}
        uses: EndBug/add-and-commit@v9
        with:
          tag: commit-${{ steps.get-data.outputs.updated }}
