name: Try to update clangd-for-modules

on:
  schedule:
    - cron: 0 1 * * *

  workflow_dispatch:

jobs:
  try-to-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: update clangd-for-modules
        run: git submodule update --init --remote --depth=1 clangd-for-modules

      - name: Commit updated submodule if changed
        uses: EndBug/add-and-commit@v9
        with:
          tag: commit-${{ steps.get-data.outputs.updated }}
